services:
  map-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - PORT=${{ shared.PORT }}
      - SPRING_DATASOURCE_URL=${{ shared.MAP_DB_URL }}
      - SPRING_DATASOURCE_USERNAME=${{ shared.MAP_DB_USERNAME }}
      - SPRING_DATASOURCE_PASSWORD=${{ shared.MAP_DB_PASSWORD }}
      - KAFKA_BOOTSTRAP_SERVERS=${{ shared.KAFKA_BOOTSTRAP_SERVERS }}
      - MAP_API_KEY=${{ shared.MAP_API_KEY }}
    restart: always